# -*- coding: utf-8 -*-
"""EVALUATIONL2PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0hNntzY3GIr0R8VhEE19Vcn7oFioKdK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- CHARGEMENT DES DONNÉES ---
# Assure-toi d'avoir chargé le fichier diabetes.csv sur Colab
df = pd.read_csv('diabetes.csv')
data = df.to_numpy()

# Extraction des colonnes pour faciliter les calculs
Pregnancies = df['Pregnancies'].to_numpy()
Glucose = df['Glucose'].to_numpy()
BloodPressure = df['BloodPressure'].to_numpy()
SkinThickness = df['SkinThickness'].to_numpy()
Insulin = df['Insulin'].to_numpy()
BMI = df['BMI'].to_numpy()
DiabetesPedigreeFunction = df['DiabetesPedigreeFunction'].to_numpy()
Age = df['Age'].to_numpy()
Outcome = df['Outcome'].to_numpy()

# --- ANALYSE STATISTIQUE ---

# 1) Nombre total de patientes
print(f"Nombre de patientes : {len(data)}")

# 2) Répartition des diagnostics (0: sain, 1: diabétique)
somme = np.sum(Outcome)
print(f"Nombre de personnes atteintes : {somme}")
print(f"Nombre de personnes saines : {len(data) - somme}")

# 3) Âge moyen
print(f"Âge moyen des patients : {np.mean(Age):.2f} ans")

# 4) Extrêmes des grossesses
print(f"Grossesses - Max : {np.max(Pregnancies)}, Min : {np.min(Pregnancies)}")

# 5) Vérification des valeurs manquantes par patient
# Exemple pour le patient 0 et 100
def verifier_patient(id):
    print(f"\nAnalyse du patient {id} :")
    colonnes = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'Age']
    for col in colonnes:
        if df.loc[id, col] == 0:
            print(f"Valeur manquante pour : {col}")

verifier_patient(0)
verifier_patient(100)

# 6) Comptage des patientes ayant au moins une valeur à 0
a = 0
for i in range(len(data)):
    if (Glucose[i] == 0 or BloodPressure[i] == 0 or SkinThickness[i] == 0 or
        Insulin[i] == 0 or BMI[i] == 0 or Age[i] == 0):
        a += 1
print(f"\nNombre de patientes avec au moins une caractéristique à zéro : {a}")

# 9 & 10) Nettoyage et séparation (Focus sur le Glucose)
listeS = [] # Sains
listeM = [] # Malades
for k in range(len(Outcome)):
    if Glucose[k] != 0: # On écarte les valeurs manquantes
        if Outcome[k] == 0:
            listeS.append(Glucose[k])
        else:
            listeM.append(Glucose[k])

# 11) Calcul des moyennes après nettoyage
print(f"\nMoyenne Glucose sain : {np.mean(listeS):.2f}")
print(f"Moyenne Glucose malade : {np.mean(listeM):.2f}")

# 12) Visualisation
plt.figure(figsize=(10, 6))
plt.hist(listeM, alpha=0.5, label='Diabétiques', color='red')
plt.hist(listeS, alpha=0.5, label='Sains', color='blue')
plt.title('Répartition du taux de Glucose selon le diagnostic')
plt.xlabel('Taux de Glucose')
plt.ylabel('Nombre de patientes')
plt.legend()
plt.show()