# -*- coding: utf-8 -*-
"""filtrage d'image par python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjwTnNbM1aVUvqYBBU5GSLeZ61zoc56-
"""

import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras import layers, models
import tensorflow as tf

(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

(number of image , shape of image)

print(x_train.shape)

(6000,28,28,1)

plt.imshow(x_train[10])

plt.imshow(x_train[1000],cmap='gray')
print(x_train[1000])

plt.imshow(x_train[5],cmap='grey')
print(x_train[5])

print(x_train.shape)

x_train=x_train.reshape(-1,28,28,1)
#x_train=x_train.reshape(6000,28,28,1)
print(x_train.shape)

x_train=x_train.reshape(-1,28,28,1).astype("float32")/255

x_test=x_test.reshape(-1,28,28,1).astype("float32")/255

model=models.Sequential(
    [
        layers.Conv2D(filters=64,kernel_size=(3,3),strides=1,padding="same",
                      activation="relu",input_shape=(28,28,1)),
        layers.MaxPool2D((2,2),strides=2),
        layers.Conv2D(filters=32,kernel_size=(3,3),strides=1,padding="same",
                      activation="relu",input_shape=(28,28,1)),
        layers.MaxPool2D((2,2),strides=2),

        layers.Flatten(),
        layers.Dense(64,activation="relu"),
        layers.Dense(10,activation='sigmoid')
    ]
)
print(model.summary())

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=5,verbose=1)

plt.plot(history.histoty['accuracy'])

x_train=x_train.reshape(6000,28,28,1).astype("float32")/255

x_test=x_test.reshape(6000,28,28,1).astype("float32")/255

model=models.Sequential(
    [
        layers.Conv2D(filters=64,kernel_size=(3,3),strides=1,padding="same",
                      activation="relu",input_shape=(28,28,1)),
        layers.MaxPool2D((2,2),strides=2),
        layers.Conv2D(filters=32,kernel_size=(3,3),strides=1,padding="same",
                      activation="relu",input_shape=(28,28,1)),
        layers.MaxPool2D((2,2),strides=2),

        layers.Flatten(),
        layers.Dense(128,activation="relu"),
        layers.Dense(10,activation='softmax')
    ]
)
print(model.summary())

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=10,verbose=1)

test_loss,test_acc=model.evaluate(x_test,y_test)

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=50,verbose=1)

test_loss,test_acc=model.evaluate(x_test,y_test)