# -*- coding: utf-8 -*-
"""CODESL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z3oDN20DmoVkWJpX6Qg03qx4Wy7HEkgf
"""

# --- EXERCICES DE BASE ---

# Exercice 1 : Salutation
prenom=input("prenom?")
nom=input("nom?")
print("Bonjour", prenom, nom)

# Exercice 2 : Initiales
prenom=input("prenom?")
nom=input("nom?")
print(prenom[0]+nom[0])

# Exercice 3 : Découpage de date
date=input("Saisir une date aaaammjj")
annee=date[0:4]
mois=date[4:6]
jour=date[6:]
print("la date est "+jour+"/"+mois+"/"+annee)

# Exercice 4 : Comparaison de date avec aujourd'hui
date = input("Saisir une date aaaammjj")
annee = date[0:4]
mois = date[4:6]
jour = date[6:]
import datetime
now=datetime.datetime.now()
annee=int(annee)
mois=int(mois)
jour=int(jour)
if annee<now.year:
    print("date passée")
elif annee>now.year:
    print("date futur")
else:
    if mois<now.month:
        print("date passée")
    elif mois>now.month:
        print("date futur")
    else:
        if jour<now.day:
            print("date passée")
        elif jour>now.day:
            print("date futur")
        else:
            print("date actuelle")

# Exercice 5 : Filtrage de liste
liste=[24,57,7845,451,8745,1,8444,45]
s=100
liste2=[]
for i in liste:
    if i<s:
        liste2.append(i)
print(liste2)


# --- MINI PROJET : JEU DU NOMBRE DEVINETTE ---

from random import randint
nombre=randint(0,100)
reponse=input("choississez un nombre entre 0 et 100")
reponse=int(reponse)
a=1
while reponse!=nombre:
    a=a+1
    if reponse<nombre:
        reponse=input("choississez un nombre plus grand")
        reponse = int(reponse)
    else:
        reponse=input("choississez un nombre plus petit")
        reponse = int(reponse)
print("Vous avez trouvé et vous avez tenté ",a," fois")


# --- ANALYSE DE DONNÉES (Dataset Heart) ---
# Note : Il faut avoir le fichier TD1_heart.csv pour que cette partie fonctionne

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lecture du fichier
df = pd.read_csv('TD1_heart.csv')
nom = df.columns.tolist()
data = df.to_numpy()

# Étude de l'âge
age_malade=[]
age_sain=[]
for k in range(len(data)):
    if data[k,-1]==0 :
        age_sain.append(data[k,0])
    else:
        age_malade.append(data[k,0])
age_malade = np.array(age_malade)
age_sain=np.array(age_sain)
moyenne=np.mean(age_malade[0:])
max=np.max(age_malade[0:])
min=np.min(age_malade[0:])
ecarttype=np.std(age_malade[0:])
print("moyenne age malade ",moyenne,"max age malade ",max,"min age malade ",min,"ET age malade",ecarttype)

# Étude du cholestérol
chol_malade=[]
chol_sain=[]
for k in range(len(data)):
    if data[k,-1]==0 :
        chol_sain.append(data[k,4])
    else:
        chol_malade.append(data[k,4])
chol_malade = np.array(chol_malade)
chol_sain=np.array(chol_sain)
moyenne=np.mean(chol_malade[0:])
print("moyenne cholesterol malade ",moyenne)

# Graphique
plt.hist(age_sain, alpha=0.5, label='Sain')
plt.hist(age_malade, alpha=0.5, label='Malade')
plt.legend()
plt.show()