# -*- coding: utf-8 -*-
"""TDMachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hau1vfu_6r98CyqvYKnho8rZWG-LO4HO
"""

import tensorflow as tf

import numpy as np

bmi_list=np.array([22,24,27,29,31,34,35,37,40,42,25,28,30,32,34,36])
diabetes_list=[0,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1]

bmi=np.array(bmi_list,dtype=float)
print(np.shape(bmi))
diabetes=np.array(diabetes_list,dtype=int)

X=bmi.reshape(-1,1)
y=diabetes

from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.25)

model=tf.keras.Sequential([
      tf.keras.layers.Dense(1,activation='sigmoid',input_shape=(1,))])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss='binary_crossentropy')
history=model.fit(X_train,y_train,epochs=200,validation_data=(X_val,y_val))



import matplotlib.pyplot as plt
plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')
plt.show()

from sklearn.datasets import load_diabetes
data=load_diabetes()
X=data.data
y=data.target

X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.25)

model=tf.keras.Sequential([
      tf.keras.layers.Dense(1,activation='sigmoid',input_shape=(10,))])
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss='binary_crossentropy')
print(model.summary())

history=model.fit(X_train,y_train,epochs=200,validation_data=(X_val,y_val),verbose=0)

plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')

model=tf.keras.Sequential([
      tf.keras.layers.Dense(16,activation='relu',input_shape=(10,)),
      tf.keras.layers.Dense(1,activation='sigmoid')])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),loss='binary_crossentropy')

history=model.fit(X_train,y_train,epochs=200,validation_data=(X_val,y_val),verbose=0)
plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')

model=tf.keras.Sequential([
      tf.keras.layers.Dense(64,activation='relu',input_shape=(10,)),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(1,activation='sigmoid')
      ])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),loss='binary_crossentropy')

history=model.fit(X_train,y_train,epochs=100,validation_data=(X_val,y_val),verbose=0)
plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')

model=tf.keras.Sequential([
      tf.keras.layers.Dense(64,activation='relu',input_shape=(10,)),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(1)
      ])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1.0),loss='mse')

history=model.fit(X_train,y_train,epochs=2000,validation_data=(X_val,y_val),verbose=0)
plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')

model=tf.keras.Sequential([
      tf.keras.layers.Dense(64,activation='relu',input_shape=(10,)),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(32,activation='relu'),
      tf.keras.layers.Dense(1)
      ])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1.0),loss='mse')

history=model.fit(X_train,y_train,epochs=2000,validation_data=(X_val,y_val),verbose=0)
plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')

