# -*- coding: utf-8 -*-
"""TD IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Di6dO9fHf5X4y3XnSxtmNxePV4lV9vo9
"""

print('hello word')

print(1)

a=10
print(a)

print(type(a))

s='Hi'
print(type(s))

a=2
b=3
print(a+b)

x=[1,2,3,4,]
print(type(x))

x=['hi',1,3,'R']
print(type(x))

x=['hi',1,3,'R']
x[0:2]

my_list = [1, 2, 3, 2, 4]
my_list.remove(2)
print(my_list)

x=['hi',1,3,'R']
x.append('bye')
x[4]

x=['hi',1,3,'R']
x.append('bye')
x = [element for element in x if type(element) != str]
print(x)

r={'name':'Amir','email':'am.mousavi97@gmail.com'}
r['name']

r={'name':'KKKK','email':'bbbbbb',"homo":"palace"}
r['homo']



r={'name':'Isaac','age':20,'from':'Amiens'}
r['age']

print(5>1)

print(5<1)

print(5==4)

print(5!=4)

print(('a==c')and('b==b'))

a=10
if a<4:
  print('less than 5')
elif 5<a<8:
    print('faux')
elif a==10:
      print('vrai')

if 6==5:
  print("vrai")
elif 6!=5:
  print('faux')

i=int
y=[i]
c=0
for i in range(1,5):
  c=c+1
print(c)

x=[1,3,5,7]
for i in x:
  if i>2:
    print(i)

x=[1,3,5,7,9,10]
y=[]
c=0
for i in x:
   c=c+1
   if i==5:
    x.remove(i)
print(f'la liste {x} compte {c} tou')

d='Hello hi my name is amir'
m=(d.split())
k=m[3:5]
phrase_finale = ' '.join(k)

print(phrase_finale)

r='amir'
r.split('m')

"""print('My name is {}'.format('Isaaac'))"""

a = 'Isaac'
b = 24
print('My name is', a, 'and my age is', b)

x='I have three car , one is black, an other car is yellow and the other car is bleu'

def count_car(sentence):
  count=0
  d=sentence.lower()
  s=d.split()
  for word in s:
    if word=='car':
      count=count +1

  return count

count_car(x)

r=3.2
type(r)

"""def squar(a):
  print(a**2)
squar(3)
"""



"""squar(3)"""

def add(a,b):
 return a+b

c=add(3,2)
return c

def say_hi(name):
  return "Hi{}".format(name)

s=say_hi('Amir')

s

def add_squar(a,b):
  d=a+b
  c=d**2
  return c

w=add_squar(a,b)
print(w)



r="2"
e=int(r)

type(e)

e=int("2")+2
print(e)

my_list=["1","2","3","hi"]
sum=0
for number in my_list:
  try:
   number=int(number)
   sum=sum+number
  except:
   print("error")
print(sum)

my_list=["1","2","3"]
sum=0
for number in my_list:
   number=int(number)
   sum=sum+number
print(sum)

t=int("2")+2
print(t)

r=input('write your name')

r

type(r)

question_1=input('2+2? ')

print(question_1)

type(question_1)

question_1=input("2+2 ? ")

if int(question_1)==4:
   print("correct")

elif int(question_1)!=4:
   print("incorrect")

question_2=input("color of sky ? ",)
if question_2 =="bleu":
   print("correct")
else:
   print("incorrect")

n=10
while n!=0:
  n=n-1
  if n<5:
    continue
  else :
   print(n)

n=10
c=0
while n!=0:
  c=c+1
  n= n-1

print(c)

password=input('Please inter your password')
while password !='python123':
  print('incorrect')
  password=input('Please inter your password: ')
else :
  print('correct')
  print('Your password is' ,password )
  print('welcome')

divisors = [5,0,2]
for d in divisors:
  try:
    print(10/d)

  except:
    print('Cannot divide by zero, skipping. ')



"""nums = [1,2,3,4,5]
n = [n**2 for n in nums]
print(n)



"""

nums = [1,2,3,4,5]
a =[]
for i in nums:
  a.append(i**2)
print(a)

data=["12","7","oops","35.5","42"]
sum=0
for number in data:
  try:
   number=float(number)
   sum=sum+number
  except ValueError:
    print()
print(sum)

"""e="12"
e=float(e)
print(type(e))
"""

import numpy as np

w=np.zeros((4,5))
w

"""import numpy
w=numpy.zeros((4,5))

import numpy
w=numpy.zeros((4,5))
"""

my_list=[[1,2,3],[4,5,6]]
type(my_list)

"""r=np.array(my_list)

r=np.array(my_list)
type(r)
"""

import numpy as np

e=np.ones((5,5))
e

n=np.eye(5)
n

"""np.arange"""

e=np.ones((3,4))
print(np.shape(e))
e

r=e.reshape((2,6))
r

np.shape(r)

e=[3,5,6,7,-1,-4]
b=np.array(e)
print(b[b>3])

d=np.linspace(1,10,5)
d

d=np.linspace(-10,10,5)
d

print(d.min())
print(d.mean())
print(d.max())

import matplotlib.pyplot as plt

x=np.arange(0,10)
y=np.arange(0,10)

plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Line')

x=np.linspace(0,2*np.pi,100)
y=np.sin(x)
plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Sine')

x=np.linspace(0,2*np.pi,100)
y=np.cos(x)
plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Sine')

x=np.linspace(0,4*np.pi,100)
y=np.cos(x)
plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Sine')

from sklearn.linear_model import LogisticRegression



import numpy as np
bmi_list=np.array([22,24,27,29,31,34,35,37,40,42,25,28,30,32,34,36])
diabetes_list=[0,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1]

bmi = np.array(bmi_list, dtype=float)
diabetes = np.array(diabetes_list, dtype=int)



X=bmi.reshape((16,1))
y=diabetes
model=LogisticRegression()
model.fit(X,y)

new_bmi=[26,36]
new_bmi=np.array(new_bmi,dtype=float).reshape(2,1)
model.predict(new_bmi)

from sklearn.linear_model import LogisticRegression

hours_list=np.array([0,1,2,3,4,5,6,7,8,9,10])
passed_list=[0,0,0,0,0,1,1,1,1,1,1,]

hours = np.array(hours_list, dtype=float)
passed = np.array(passed_list, dtype=int)

X=hours.reshape((11,1))
y=passed
model=LogisticRegression()
model.fit(X,y)

new_hours=[[2],[5],[8]]
new_hours=np.array(new_hours,dtype=float).reshape(3,1)
model.predict(new_hours)

"""TD 26/11

"""

import tensorflow as tf

import numpy as np

bmi_list=np.array([22,24,27,29,31,34,35,37,40,42,25,28,30,32,34,36])
diabetes_list=[0,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1]

bmi=np.array(bmi_list,dtype=float)
print(np.shape(bmi))
diabetes=np.array(diabetes_list,dtype=int)

X=bmi.reshape(-1,1)
y=diabetes

from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.25)

model=tf.keras.Sequential([
      tf.keras.layers.Dense(1,activation='sigmoid',input_shape=(1,))])
model.compile(optimizer=tf.tf.keras.optimizers.Adam(learning_rate=0.001),loss='binary_crossentropy')
history=model.fit(X_train,y_train,epochs=200,validation_data=(X_val,y_val))

import matplotlib.pyplot as plt
plt.plot(history.history['loss'],label='train')
plt.plot(history.history['val_loss'],label='val')

from sklearn.datasets import load_diabetes

"""CODE VALUATION A"""

x=3
y=2.5
z="5"
a=x+y
b=str(x)+z
c=int(z)+x
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))



"""CODE EVALUATION QUESTION A.2"""

age = 17
if age >=18:
   message="adult"
elif age>=13:
  message="teenager"
else:
  message="child"
print(message)

"""CODE EVALUATION  3"""

nums=[1,2,3,4]
total=0
for n in nums:
   total = total+n
print(total)

nums = [1, 2, 3, 4]
total = 0
for n in [len(nums)]:
    total += n

print(total)

"""CODE PART B"""

age_list = [45, 62, 31, 55, 70, 28, 50, 68, 40, 58, 35, 75, 48, 60, 39, 53, 42, 65, 33, 72]
bmi_list = [28.5, 31.2, 22.9, 35.0, 26.1,
24.5, 29.0, 33.5, 25.1, 30.5,
23.0, 27.8, 29.9, 32.1, 24.0,
34.2, 26.5, 30.0, 22.5, 36.1]
diabetes_list = [0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1]

print("Shape of bmi_list:", bmi_list.shape)
print("Mean of bmi_list:", bmi_list.mean())
print("Standard deviation of bmi_list:", bmi_list.std())

"""Part 4.5"""

age_list = [45, 62, 31, 55, 70, 28, 50, 68, 40, 58, 35, 75, 48, 60, 39, 53, 42, 65, 33, 72]
bmi_list = [28.5, 31.2, 22.9, 35.0, 26.1,
24.5, 29.0, 33.5, 25.1, 30.5,
23.0, 27.8, 29.9, 32.1, 24.0,
34.2, 26.5, 30.0, 22.5, 36.1]
diabetes_list = [0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1]

print("Shape of bmi_list:", bmi_list.shape)
print("Mean of bmi_list:", bmi_list.mean())
print("Standard deviation of bmi_list:", bmi_list.std())

import matplotlib.pyplot as plt
import numpy as np

# Assuming bmi_list is already defined as a numpy array
# If it's a Python list, convert it to a numpy array first
# bmi_list_np = np.array(bmi_list)

patient_indices = np.arange(len(bmi_list))

plt.figure(figsize=(10, 6))
plt.plot(patient_indices, bmi_list, marker='o', linestyle='-')
plt.xlabel('Patient Index')
plt.ylabel('BMI Value')
plt.title('BMI Values vs. Patient Index')
plt.grid(True)
plt.show()

age_list = [45, 62, 31, 55, 70, 28, 50, 68, 40, 58, 35, 75, 48, 60, 39, 53, 42, 65, 33, 72]
bmi_list = [28.5, 31.2, 22.9, 35.0, 26.1,
24.5, 29.0, 33.5, 25.1, 30.5,
23.0, 27.8, 29.9, 32.1, 24.0,
34.2, 26.5, 30.0, 22.5, 36.1]
diabetes_list = [0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1]

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

age_list = np.array([45, 62, 31, 55, 70, 28, 50, 68, 40, 58, 35, 75, 48, 60, 39, 53, 42, 65, 33, 72])
bmi_list = np.array([28.5, 31.2, 22.9, 35.0, 26.1,
24.5, 29.0, 33.5, 25.1, 30.5,
23.0, 27.8, 29.9, 32.1, 24.0,
34.2, 26.5, 30.0, 22.5, 36.1])
diabetes_list = np.array([0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1])

# Create the feature matrix X and target vector y
X = np.column_stack((age_list, bmi_list))
y = diabetes_list

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Compute and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on test Data: {accuracy:.2f}")

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Define the CNN model
model = Sequential()

# 1st convolutional layer
model.add(Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(28,28,1)))
# 1st max pooling
model.add(MaxPooling2D(pool_size=(2,2)))

# 2nd convolutional layer
model.add(Conv2D(filters=64, kernel_size=(3,3), activation='relu'))
# 2nd max pooling
model.add(MaxPooling2D(pool_size=(2,2)))

# Flatten the feature maps to feed into Dense layers
model.add(Flatten())

# Fully connected layer
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))  # to reduce overfitting

# Output layer: 10 classes, softmax activation
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Summary of the model
model.summary()